# Generated by Django 4.0.4 on 2022-07-19 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jeopardy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('GE', 'General'), ('SH', 'Shows'), ('MO', 'Movies'), ('SP', 'Sports'), ('WE', 'Weather'), ('HI', 'history')], default='GE', max_length=2)),
                ('name', models.CharField(max_length=2000)),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(max_length=2000)),
                ('clue', models.CharField(max_length=2000)),
                ('cluevalue', models.IntegerField(choices=[(100, 'One'), (200, 'Two'), (300, 'Three'), (400, 'Four'), (500, 'Five')])),
                ('answer', models.CharField(max_length=2000)),
                ('choiceone', models.CharField(max_length=2000)),
                ('choicetwo', models.CharField(max_length=2000)),
                ('choicethree', models.CharField(max_length=2000)),
                ('answered', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jeopardy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
