# Generated by Django 4.0.4 on 2022-07-19 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0004_rename_questions_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='cluevalue',
            field=models.IntegerField(choices=[(100, 'Onehundred'), (200, 'Twohundred'), (300, 'Threehundred'), (400, 'Fourhundred'), (500, 'Fivehundred')]),
        ),
        migrations.AlterField(
            model_name='jeopardy',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeopardy.subject'),
        ),
    ]
