# Generated by Django 4.0.4 on 2022-07-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0005_subject_alter_question_cluevalue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryone', models.CharField(max_length=2000)),
                ('categorytwo', models.CharField(max_length=2000)),
                ('categorythree', models.CharField(max_length=2000)),
                ('categoryfour', models.CharField(max_length=2000)),
                ('categoryfive', models.CharField(max_length=2000)),
            ],
        ),
    ]
