# Generated by Django 4.0.4 on 2022-07-19 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0006_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
