# Generated by Django 4.0.4 on 2022-07-19 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0007_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='jeopardy',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('jeopardy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeopardy.jeopardy')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeopardy.category'),
        ),
    ]
