# Generated by Django 4.0.4 on 2022-07-26 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0008_remove_question_jeopardy_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answered',
        ),
        migrations.AddField(
            model_name='question',
            name='player',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='choice',
            field=models.CharField(max_length=50),
        ),
    ]
