# Generated by Django 4.0.4 on 2022-07-26 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0009_remove_question_answered_question_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='player',
        ),
    ]
