# Generated by Django 4.0.4 on 2022-07-27 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0011_question_answered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['cluevalue']},
        ),
    ]
